/**
 * Download SVG file to user's device
 * @param svg - SVG string
 * @param filename - Filename for download
 */
export const downloadSVG = (svg: string, filename: string): void => {
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';

    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, 100);
};

/**
 * Add metadata to SVG
 * @param svg - SVG string
 * @returns SVG with metadata
 */
export const addSVGMetadata = (svg: string): string => {
    const metadata = `<!-- Generated by Isometric Voxel Builder -->
<!-- https://isometric-voxel-builder.app -->`;

    return svg.replace('<svg', `${metadata}\n<svg`);
};

/**
 * Generate filename with timestamp
 * @returns Filename string
 */
export const generateFilename = (): string => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    return `isometric-voxel-${timestamp}.svg`;
};
